// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7dd-SYChNeB3REBfW9i1IUJysLCXHQI',
    appId: '1:529992144983:web:c1a3026386ee35c3db6b12',
    messagingSenderId: '529992144983',
    projectId: 'ect-project-188c8',
    authDomain: 'ect-project-188c8.firebaseapp.com',
    storageBucket: 'ect-project-188c8.appspot.com',
    measurementId: 'G-J28HREE766',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNcipBM2rznNsrHCbON6nLXc5HQwYzKA',
    appId: '1:529992144983:android:0059641fbe255497db6b12',
    messagingSenderId: '529992144983',
    projectId: 'ect-project-188c8',
    storageBucket: 'ect-project-188c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbOKtAurxjvLD4rkdPfnK0wOBUZJXBs0',
    appId: '1:529992144983:ios:9bf6a181726ad800db6b12',
    messagingSenderId: '529992144983',
    projectId: 'ect-project-188c8',
    storageBucket: 'ect-project-188c8.appspot.com',
    iosClientId: '529992144983-l39drpctidk95vqtlb1bgj3799nchtek.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTbOKtAurxjvLD4rkdPfnK0wOBUZJXBs0',
    appId: '1:529992144983:ios:9bf6a181726ad800db6b12',
    messagingSenderId: '529992144983',
    projectId: 'ect-project-188c8',
    storageBucket: 'ect-project-188c8.appspot.com',
    iosClientId: '529992144983-l39drpctidk95vqtlb1bgj3799nchtek.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
